services:
  app:
    build:
      context: .
      dockerfile: test/flask/Dockerfile
    ports:
      - 5001:8080
    volumes:
      - ./test/flask/app:/app/app
      - ./test/playwright:/app/playwright-tests
      - ./test/test-fixtures.mjs:/app/test-fixtures.mjs
      - ./test/flask/pyproject.toml:/app/pyproject.toml
      - ./test/flask/poetry.lock:/app/poetry.lock
      - ./tna_frontend_jinja:/app/tna_frontend_jinja
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./node_modules:/app/node_modules
      - ./.nvmrc:/app/.nvmrc
      - ./.prettierignore:/app/.prettierignore
      - ./hatch_build.py:/app/hatch_build.py
      - ./docs:/app/docs
    healthcheck:
      start_period: 10s
      start_interval: 2s

  django:
    build:
      context: .
      dockerfile: test/django/Dockerfile
    ports:
      - 8001:8000
    volumes:
      - ./test/django/app:/app/test/django/app
      - ./tna_frontend_jinja:/app/tna_frontend_jinja
      - ./README.md:/app/README.md
      - ./pyproject.toml:/app/pyproject.toml
      - ./LICENCE:/app/LICENCE
    command: ["python", "test/django/app/manage.py", "runserver", "0.0.0.0:8000"]

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - 5002:8000
